### ISSUE TITLE
Error: Unknown plugin "add-module-exports" 

### ISSUE THREAD

**Issue by jasonzhouu** [okonet/react-dropzone#383]
I use example in the README, but get a error.
```
ERROR in ./~/react-dropzone/dist/index.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/admin/Coding_Project/online-presentation/node_modules/react-dropzone/.babelrc" at 0, attempted to resolve relative to "/Users/admin/Coding_Project/online-presentation/node_modules/react-dropzone"
    at /Users/admin/Coding_Project/online-presentation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/admin/Coding_Project/online-presentation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/admin/Coding_Project/online-presentation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/admin/Coding_Project/online-presentation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/admin/Coding_Project/online-presentation/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/admin/Coding_Project/online-presentation/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/admin/Coding_Project/online-presentation/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/admin/Coding_Project/online-presentation/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/admin/Coding_Project/online-presentation/node_modules/babel-loader/lib/index.js:134:16)
 @ ./scripts/reducers/DropzoneDemo.js 12:21-46
 @ ./scripts/index.js
```
My file is like this:
DropzoneDemo.js
```
import React from 'react';
import Dropzone from 'react-dropzone';

var DropzoneDemo = React.createClass({
    onDrop: function (files) {
      console.log('Received files: ', files);
    },

    render: function () {
      return (
          <div>
            <Dropzone onDrop={this.onDrop}>
              <div>Try dropping some files here, or click to select files to upload.</div>
            </Dropzone>
          </div>
      );
    }
});

export default DropzoneDemo;
```
index.js
```
import React from 'react';
import ReactDOM from 'react-dom';

import DropzoneDemo from './reducers/DropzoneDemo.js';

ReactDOM.render(
  <DropzoneDemo />,
  document.getElementById('uploadFile')
);
```
browser:   newest Chrome
Operating System:   macOS Sierra 10.12.3
react-dropzone version:   ^3.12.0

**Comment by okonet** [comment]
Did you install it via npm? You seem to transpile the source of dropzone with your babel. You should exclude external libraries from your transpilation step.

**Comment by wbecker** [comment]
I'm just found that I'm having this problem as well - only on windows though. I thought babel didn't transpile modules by default?

**Comment by wbecker** [comment]
could you solve this @jasonzhouu ?

**Comment by RagingKore** [comment]
@okonet Hi, I'm having the same issue and my babel file is configured to ignore modules 

``` json
{
  "presets": [
    [
      "es2015",
      {
        "loose": true,
        "modules": false,
        "useBuiltIns": true
      }
    ],
    "stage-2",
    "react"
  ],

  "env": {
    "production": {
      "presets": [
        "react-optimize"
      ]
    },
    "development": {
      "compact": false,
      "plugins": [
        "react-hot-loader/babel",
        "transform-react-jsx-source"
      ]
    }
  }
}

```

Am I missing something here?

Thanks

**Comment by elliotrock** [comment]
@okonet you mention "You should exclude external libraries from your transpilation step" but give no example of how to do this. You mention this in the documentation a well. Could you please add thank you.

**Comment by elliotrock** [comment]
The solution as an example:

```
module: {
        loaders: [
            {
                test: /\.js[x]?$/,
                loader: 'babel-loader',
                **exclude: /node_modules/**
            },
            {
                test: /\.css$/,
                loader: 'css-loader'
            }
        ],   
    }
```

**Comment by figalex** [comment]
I'm trying to do server side rendering on a component using react-dropzone and I get this same error. I already added `exclude: /node_modules/` and still have this issue. Any idea what could I be doing wrong?

**Comment by nnnikolay** [comment]
I use **[parcel](https://github.com/parcel-bundler/parcel)** and had the same issue, to solve it I  added into `.babelrc` following line 

```
  "ignore": [
    "node_modules"
  ]
```

and it's solved the problem

**Comment by ksaitor** [comment]
@nnnikolay i'm on parcel as well. Did this:
```
{
  "presets": ["env", "react"],
  "ignore": [
    "node_modules"
  ]
}
```
but it did not solve the issue 😢  How did you solve it?

**Comment by nnnikolay** [comment]
@ksaitor Try to remove `node_modules` and run `npm i` having mentioned config in the folder. I'm not was it config changes or reinstallation all the modules. But now I don't have it.

**Comment by ksaitor** [comment]
@nnnikolay  😞  same… I'm on node v8.4.0 btw…

**Comment by nnnikolay** [comment]
@ksaitor I don't know can it help or not but I'm using 
```
$ node -v
v9.3.0
```

and 

```
  "dependencies": {
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-dropzone": "4.2.3",
```

**Comment by jeremy-dimasuay** [comment]
Piggybacking off of [this example](https://github.com/react-dropzone/react-dropzone/issues/383#issuecomment-296506904), here's an example if you need/want to individually exclude `react-dropzone`:

```
{
    test: /\.jsx?$/,
    include(filepath) {
        if (filepath.includes('react-dropzone')) return false;
    
        return true;
    }
}
```
